# SPARQL query to select provenance information at feature and attribute levels
SELECT ?feature ?region ?popBornValue ?kgNum ?source ?referceSystem
       ?sourceLevel ?processInfo 
WHERE { ?feature dex:hasProperty ?popBornProperty .
        ?popBornProperty a dex:PopBorn .
        ?popBornProperty dex:value ?popBornValue .
        FILTER(?popBornValue >= 1500) .
        ?feature dex:hasProperty ?kgNumProperty .
        ?kgNumProperty a dex:KindergartenNum .
        ?kgNumProperty dex:value ?kgNum .
        ?feature dex:inRegion ?region .
        ?source prov:hadMember ?feature .
        ?source li:sourceReferenceSystem ?RS .
        ?RS md:referenceSystemIdentifier ?RS_id .
        ?RS_id md:code ?referceSystem .
        ?source li:scope ?scope .
        ?scope md:level ?sourceLevel .
        ?process li:output ?source .
        ?process li:processingInformation ?processInfo .}